services:
  app:
    build: .
    container_name: Video-streaming-service
    ports:
      - "8080:8080"
    environment:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=password
    depends_on:
      - minio
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: password
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: server /data
